controller:
  rbac:
    create: true
    scope: true
  scope:
    enabled: true
    namespace: shir
  service:
    type: LoadBalancer
  ingressClassResource:
    name: shir
    enabled: true
    default: true
    controllerValue: "k8s.io/ingress-nginx"
  extraArgs:
    update-status: "false"
