apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: shir
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: 992382545251.dkr.ecr.us-east-1.amazonaws.com/shir/k8s:wordpress
          ports:
            - containerPort: 80
          env:
            - name: WORDPRESS_DB_HOST
              value: mariadb
            - name: WORDPRESS_DB_USER
              value: wordpress
            - name: WORDPRESS_DB_PASSWORD
              value: wordpress
            - name: WORDPRESS_DB_NAME
              value: wordpress
          volumeMounts:
            - name: wordpress-data-shir
              mountPath: /var/www/html
      volumes:
        - name: wordpress-data-shir
          persistentVolumeClaim:
            claimName: wordpress-pvc-shir  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc-shir
  namespace: shir
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ebs-sc-nitzanim

